In [5]:
import numpy as np 

a : np.ndarray = np.array(100)

print(a)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.itemsize)

100
()
int64
1
8


In [6]:
data = [[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]]

a : np.ndarray = np.array(data)

print(a)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.itemsize)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
int64
12
8


In [7]:
data = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a : np.ndarray = np.array(data)

print(a)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.itemsize)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
int64
10
8


## Typing Support: NDArray

In [4]:
from nptyping import NDArray, Shape, UInt64
from typing import Any
import numpy as np

data: NDArray[Shape["10"], Any] = np.arange(1,11)

print(data)

# this would not be possible in python's list (array) 
modified_data = data + 5
print(modified_data)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]
